"use client";

import * as React from "react";

import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import { useSearchStore } from "@/lib/stores/useSearchStore";
import {
  CircleMinus,
  CircleX,
  LocateFixed,
  LocateFixedIcon,
  LocateIcon,
  LocateOffIcon,
  MapPin,
  RemoveFormatting,
  RemoveFormattingIcon,
} from "lucide-react";

function EstateFilter() {
  const useHistory = useSearchStore();
  const inputRef = React.useRef<HTMLInputElement>(null);

  return (
    <div className="w-full border rounded-md  flex items-center justify-center  ">
      <div className="flex items-center justify-center flex-col">
        <Command className="w-96">
          <div>
            <CommandInput
              placeholder="Procure por cidade ou estado"
              ref={inputRef}
            />
          </div>
          <CommandList>
            <CommandEmpty>Nenhum resultado.</CommandEmpty>
            <CommandGroup heading="Histórico">
              {useHistory.history.map((history, index) => {
                return (
                  <div
                    className="flex items-center justify-between text-sm w-full gap-x-2 px-2 py-1 cursor-pointer"
                    key={index}
                  >
                    <div className="flex items-center gap-x-2">
                      <div className="flex items-center justify-center h-full space-x-2">
                        <MapPin size={10} className="text-muted-foreground" />
                      </div>
                      <div className="text-xs">
                        <span className=""> {history.city} - </span>
                        <span className="text-muted-foreground font-bold">
                          {history.estate}
                        </span>
                      </div>
                    </div>
                    <div>
                      <CircleX
                        size={15}
                        className="text-muted-foreground cursor-pointer hover:bg-accent-foreground transition-all rounded-full hover:text-white"
                        onClick={() => {
                          useHistory.remove(history.city);
                        }}
                      />
                    </div>
                  </div>
                );
              })}
            </CommandGroup>

            <CommandGroup heading="Sugestões">
              {data.map((estate) =>
                estate.municipios.map((item, index) => (
                  <CommandItem
                    className="cursor-pointer"
                    key={index}
                    onClickCapture={() => {
                      useHistory.add({
                        city: item,
                        estate: estate.name,
                      });
                    }}
                  >
                    <MapPin />
                    <div className="text-xs">
                      <span className=""> {item} - </span>
                      <span className="text-muted-foreground font-bold">
                        {estate.name}
                      </span>
                    </div>
                  </CommandItem>
                ))
              )}
            </CommandGroup>
          </CommandList>
        </Command>
      </div>
    </div>
  );
}

export const data = [
  {
    name: "Alagoas",
    uf: "AL",
    municipios: [
      "Maceió",
      "Arapiraca",
      "Palmeira dos Índios",
      "Rio Largo",
      "Penedo",
      "União dos Palmares",
      "Coruripe",
      "Delmiro Gouveia",
      "Campo Alegre",
      "São Miguel dos Campos",
      "Teotônio Vilela",
      "Marechal Deodoro",
      "São Luís do Quitunde",
      "Joaquim Gomes",
      "Murici",
      "Limoeiro de Anadia",
      "Pilar",
      "Girau do Ponciano",
      "São José da Laje",
      "Roteiro",
      "Chã Preta",
      "Senador Rui Palmeira",
      "Água Branca",
      "Batalha",
      "Santa Luzia do Norte",
      "Maribondo",
      "Inhapi",
      "Jundiá",
      "Quebrangulo",
      "Major Isidoro",
      "Estrela de Alagoas",
      "Cacimbinhas",
      "Igreja Nova",
      "Belo Monte",
      "Coité do Nóia",
      "Porto Real do Colégio",
      "Cajueiro",
      "Santana do Ipanema",
      "Palestina",
      "Riacho do Sertão",
      "Jaramataia",
      "São Sebastião",
      "São José da Tapera",
      "Olho d'Água do Casado",
      "Olho d'Água das Flores",
      "São Miguel dos Milagres",
      "Passo de Camaragibe",
      "Maragogi",
      "Barra de São Miguel",
      "Barra de Santo Antônio",
      "São Luís do Quitunde",
      "Água Branca",
      "São José da Laje",
      "Campestre",
    ],
  },
  {
    name: "Ceará",
    uf: "CE",
    municipios: [
      "Fortaleza",
      "Caucaia",
      "Juazeiro do Norte",
      "Maracanaú",
      "Sobral",
      "Crato",
      "Iguatu",
      "Quixadá",
      "Acarape",
      "Aquiraz",
      "Aracati",
      "Aratuba",
      "Banabuiú",
      "Barbalha",
      "Baturité",
      "Beberibe",
      "Bela Cruz",
      "Brejo Santo",
      "Canindé",
      "Capistrano",
      "Caririaçu",
      "Chorozinho",
      "Ererê",
      "Forquilha",
      "General Sampaio",
      "Guaraciaba do Norte",
      "Guaramiranga",
      "Hidrolândia",
      "Horizonte",
      "Ibiapina",
      "Ibipapaba",
      "Ibiúna",
      "Ipu",
      "Itapagé",
      "Itapipoca",
      "Itarema",
      "Itaubá",
      "Jaguaretama",
      "Jaguaribe",
      "Jaguaruana",
      "Jijoca de Jericoacoara",
      "Jucás",
      "Limoeiro do Norte",
      "Madalena",
      "Mauriti",
      "Milhã",
      "Morrinhos",
      "Mucambo",
      "Mulungu",
      "Nova Russas",
      "Pacajus",
      "Pacatuba",
      "Palhano",
      "Parambu",
      "Paramoti",
      "Parangaba",
      "Penaforte",
      "Quixeramobim",
      "Quixeré",
      "Redenção",
      "São Benedito",
      "São Gonçalo do Amarante",
      "São João do Jaguaribe",
      "São Luís do Curu",
      "São Mateus",
      "São Pedro",
      "Senador Pompeu",
      "Sobral",
      "Trairi",
      "Viçosa do Ceará",
    ],
  },
  {
    name: "Pernambuco",
    uf: "PE",
    municipios: [
      "Recife",
      "Jaboatão dos Guararapes",
      "Olinda",
      "Caruaru",
      "Petrolina",
      "Cabo de Santo Agostinho",
      "Vitória de Santo Antão",
      "Igarassu",
      "Garanhuns",
      "Santa Cruz do Capibaribe",
      "Araripina",
      "Ouricuri",
      "São Lourenço da Mata",
      "Surubim",
      "Limoeiro",
      "Saloá",
      "Paudalho",
      "Xexéu",
      "Jaqueira",
      "Altinho",
      "Bezerros",
      "Brejo da Madre de Deus",
      "Cabo de Santo Agostinho",
      "Camocim de São Félix",
      "Casinhas",
      "Chã Grande",
      "Chã Preta",
      "Itaíba",
      "Itambé",
      "Itaíba",
      "Jataúba",
      "Limoeiro",
      "Machados",
      "Maraial",
      "Mirandiba",
      "Morrinhos",
      "Orobó",
      "Orocó",
      "Panelas",
      "Pedra",
      "Pesqueira",
      "Pombos",
      "Primavera",
      "Quipapá",
      "Ribeirão",
      "Sairé",
      "Salgueiro",
      "Sanharó",
      "São Bento do Una",
      "São Caetano",
      "São João",
      "São Joaquim do Monte",
      "São Vicente Férrer",
      "Serra Talhada",
      "Tupanatinga",
      "Venturosa",
      "Vicência",
      "Vila de Santo Antão",
      "Bezerros",
      "Bom Conselho",
      "Correntes",
      "Cupira",
      "Dormentes",
      "Exu",
      "Frei Miguelinho",
      "Ibipetuba",
      "Itapetim",
      "Lagoa Grande",
      "Limoeiro",
      "Manari",
      "Pombos",
      "Quipapá",
      "Santa Cruz do Capibaribe",
      "São José do Belmonte",
      "São José do Egito",
      "São Vicente Ferrer",
      "Sertânia",
      "Sirinhaém",
      "Triunfo",
      "Trindade",
    ],
  },
  {
    name: "Rio Grande do Norte",
    uf: "RN",
    municipios: [
      "Natal",
      "Mossoró",
      "Parnamirim",
      "São Gonçalo do Amarante",
      "Macaíba",
      "Caicó",
      "Currais Novos",
      "Açu",
      "São José de Mipibu",
      "Pau dos Ferros",
      "Assu",
      "Santa Cruz",
      "São Paulo do Potengi",
      "São Pedro",
      "João Câmara",
      "Tangará",
      "São Miguel",
      "Nísia Floresta",
      "Canguaretama",
      "Macau",
      "Goianinha",
      "São Tomé",
      "Japi",
      "Lajes",
      "Alexandria",
      "Areia Branca",
      "Jardim de Piranhas",
      "Mossoró",
      "Rio do Fogo",
      "Pedro Avelino",
      "Serrinha",
      "Sítio Novo",
      "Parnamirim",
      "São Fernando",
      "Santos Dumont",
      "São Vicente",
      "Currais Novos",
      "Mossoró",
      "São José do Mipibu",
      "São Rafael",
      "Riachuelo",
      "Nísia Floresta",
      "Serra de São Bento",
      "Ceará-Mirim",
      "Lagoa de Velhos",
      "Parelhas",
      "Monte Alegre",
      "Maxaranguape",
      "Tibau",
      "Jardim do Seridó",
      "Rodolfo Fernandes",
      "Carnaúba dos Dantas",
      "Janduís",
      "Lagoa Nova",
      "Ceará-Mirim",
      "Baraúna",
      "Serra Negra do Norte",
      "Janduís",
      "Parelhas",
      "Lagoa Salgada",
      "Canguaretama",
      "Rafael Fernandes",
      "Lagoa Nova",
      "Felizardo",
      "Santana do Matos",
      "Cruzeta",
      "São José do Seridó",
    ],
  },
  {
    name: "Piauí",
    uf: "PI",
    municipios: [
      "Teresina",
      "Parnaíba",
      "Picos",
      "Piripiri",
      "Floriano",
      "Bom Jesus",
      "São Raimundo Nonato",
      "Altos",
      "Cocal",
      "José de Freitas",
      "Campo Maior",
      "Barras",
      "Oeiras",
      "Uruçuí",
      "Miguel Alves",
      "Cajueiro da Praia",
      "Pedro II",
      "São João do Piauí",
      "Pau D'Arco do Piauí",
      "Cocal de Telha",
      "Vera Mendes",
      "Amarante",
      "Buriti dos Lopes",
      "Marcolândia",
      "Itaueira",
      "Teresina",
      "São José do Peixe",
      "Regeneração",
      "Juazeiro do Piauí",
      "Paulistana",
      "Sussuapara",
      "Avelino Lopes",
      "Beneditinos",
      "Coivaras",
      "Irauçuba",
      "Itainópolis",
      "Lagoa do Piauí",
      "Madeiro",
      "Matias Olímpio",
      "Morro do Chapéu do Piauí",
      "São Félix do Piauí",
      "São José do Divino",
      "Tamboril do Piauí",
      "Arraial",
      "Buriti dos Montes",
      "Cocal dos Alves",
      "Dirceu Arcoverde",
      "Inhuma",
      "Jatobá do Piauí",
      "José de Freitas",
      "Lagoa do Piauí",
      "Morrinhos",
      "Nossa Senhora de Nazaré",
      "Parnaguá",
      "Paulistana",
      "Pedro Laurentino",
      "Santa Cruz do Piauí",
      "Santa Filomena",
      "São Miguel do Tapuio",
      "Teresina",
      "Vila Nova do Piauí",
    ],
  },
  {
    name: "Rio de Janeiro",
    uf: "RJ",
    municipios: [
      "Rio de Janeiro",
      "Niterói",
      "São Gonçalo",
      "Duque de Caxias",
      "Nova Iguaçu",
      "Magé",
      "Petrópolis",
      "Volta Redonda",
      "Belford Roxo",
      "Cabo Frio",
      "Campos dos Goytacazes",
      "Angra dos Reis",
      "Macaé",
      "São João de Meriti",
      "Itaboraí",
      "Nova Friburgo",
      "Três Rios",
      "Santa Maria Madalena",
      "São Pedro da Aldeia",
      "Resende",
      "Barra Mansa",
      "Paraty",
      "Seropédica",
      "Queimados",
      "Maricá",
      "Rio Bonito",
      "Araruama",
      "Sapucaia",
      "Itaocara",
      "Iguaba Grande",
      "Rio das Ostras",
      "Cachoeiras de Macacu",
      "Miguel Pereira",
      "Paty do Alferes",
      "Valença",
      "Conceição de Macabu",
      "Tanguá",
      "São Sebastião do Rio de Janeiro",
      "Aperibé",
      "Cantagalo",
      "Engenheiro Paulo de Frontin",
      "Itaperuna",
      "Japeri",
      "Piraí",
      "Porciúncula",
      "Quatis",
      "São Francisco de Itabapoana",
      "São José de Ubá",
      "Silva Jardim",
      "Sumidouro",
      "Varre-Sai",
      "Volta Redonda",
      "Vassouras",
      "Paraíba do Sul",
      "Campos do Jordão",
      "Vila Valqueire",
      "São João Nepomuceno",
    ],
  },
  {
    name: "Bahia",
    uf: "BA",
    municipios: [
      "Salvador",
      "Feira de Santana",
      "Vitória da Conquista",
      "Camaçari",
      "Itabuna",
      "Juazeiro",
      "Ilhéus",
      "Lauro de Freitas",
      "Eunápolis",
      "Barreiras",
      "Porto Seguro",
      "Santa Maria da Vitória",
      "Simões Filho",
      "Alagoinhas",
      "Valença",
      "Teixeira de Freitas",
      "Candeias",
      "Senhor do Bonfim",
      "Paulo Afonso",
      "Macaúbas",
      "Irecê",
      "Piritiba",
      "São Sebastião do Passé",
      "Jequié",
      "Bom Jesus da Lapa",
      "Araci",
      "Canarana",
      "Andaraí",
      "Ipirá",
      "Santo Amaro",
      "Sapeaçu",
      "Riachão do Jacuípe",
      "Jacuípe",
      "Candeias",
      "Casa Nova",
      "Santa Teresinha",
      "Laje",
      "São Félix",
      "Nova Soure",
      "Coaraci",
      "Livramento de Nossa Senhora",
      "Abaré",
      "Pau Brasil",
      "Banzaê",
      "Sento Sé",
      "Barrocas",
      "Tucano",
      "São Desidério",
      "Euclides da Cunha",
      "São Francisco do Conde",
      "Açu da Boa Vista",
      "Mairi",
      "Paratinga",
      "Igaporã",
      "Coração de Maria",
      "São Miguel das Matas",
      "Lagoa do Colégio",
      "Ibipetuba",
      "Monte Santo",
      "Sítio do Mato",
      "Santa Brígida",
      "Antônio Cardoso",
      "Cairu",
    ],
  },
  {
    name: "Amapá",
    uf: "AP",
    municipios: [
      "Macapá",
      "Santana",
      "Laranjal do Jari",
      "Oiapoque",
      "Tartarugalzinho",
      "Porto Grande",
      "Cutias",
      "Amapá",
      "Ferreira Gomes",
      "Calçoene",
      "Pedra Branca do Amapari",
      "Pracuúba",
      "Itaubal",
      "Tucuruí",
      "Mazagão",
      " Vitória do Jari",
      "Serra do Navio",
      "Jari",
      "Montezuma",
      "Câmara de Vereadores",
      "Rumo do Cazumbá",
      "Caiçara do Norte",
      "Caiçara do Sul",
      "Itapeu",
      "Santa Luzia do Norte",
      "Bom Jesus do Amapá",
      "São João da Baliza",
      "Sao Raimundo do Jari",
      "Curiaú",
      "Alto Alegre",
      "Amapi",
      "Barão de Mauá",
      "Caracaraí",
      "Melançon",
      "Serra Dourada",
      "Capanema",
      "Melgac",
    ],
  },
  {
    name: "Acre",
    uf: "AC",
    municipios: [
      "Rio Branco",
      "Cruzeiro do Sul",
      "Senador Guiomard",
      "Tarauacá",
      "Feijó",
      "Mâncio Lima",
      "Senador Guiomard",
      "Plácido de Castro",
      "Brasileia",
      "Xapuri",
      "Assis Brasil",
      "Capixaba",
      "Epitaciolândia",
      "Acrelândia",
      "Bujari",
      "Brasiléia",
      "Marechal Thaumaturgo",
      "Porto Walter",
      "Acrelândia",
      "Rodrigues Alves",
      "Senador Guiomard",
      "Assis Brasil",
      "Acrelândia",
      "Xapuri",
      "Bujari",
      "Epitaciolândia",
      "Capixaba",
      "Acrelândia",
      "Marechal Thaumaturgo",
      "Plácido de Castro",
      "Feijó",
      "Manoel Urbano",
      "Mâncio Lima",
      "Porto Walter",
      "Rodrigues Alves",
      "Senador Guiomard",
      "Brasiléia",
      "Tarauacá",
      "Cruzeiro do Sul",
    ],
  },
  {
    name: "Amazonas",
    uf: "AM",
    municipios: [
      "Manaus",
      "Parintins",
      "Itacoatiara",
      "Coari",
      "Manacapuru",
      "Tefé",
      "Tabatinga",
      "São Gabriel da Cachoeira",
      "Boca do Acre",
      "Humaitá",
      "Nova Olinda do Norte",
      "Nhamundá",
      "Japurá",
      "Eirunepé",
      "Juruá",
      "Benjamin Constant",
      "Barcelos",
      "Atalaia do Norte",
      "Carauari",
      "São Sebastião do Uatumã",
      "Apuí",
      "Iranduba",
      "Careiro",
      "Careiro da Várzea",
      "Presidente Figueiredo",
      "Santa Isabel do Rio Negro",
      "Amaturá",
      "Alvarães",
      "Anamã",
      "Beruri",
      "Canutama",
      "Coari",
      "Envira",
      "Itapiranga",
      "Lábrea",
      "Maués",
      "Novo Airão",
      "Novo Aripuanã",
      "São Paulo de Olivença",
      "Santo Antônio do Içá",
      "São Pedro do Solimões",
      "São João da Baliza",
      "Tapauá",
      "Tapauá",
      "Uarini",
      "Urucará",
      "Urucurituba",
      "Vilhena",
      "Santa Teresa",
      "Santa Luzia do Norte",
      "Santa Teresa",
      "Santarém",
      "Santarém Novo",
      "Maués",
      "Uauá",
      "Uapá",
      "Uarini",
    ],
  },
  {
    name: "Distrito Federal",
    uf: "DF",
    municipios: ["Brasília"],
  },
  {
    name: "Espírito Santo",
    uf: "ES",
    municipios: [
      "Vitória",
      "Vila Velha",
      "Serra",
      "Cariacica",
      "Linhares",
      "Colatina",
      "Guarapari",
      "São Mateus",
      "Aracruz",
      "Nova Venécia",
      "Itapemirim",
      "Fundão",
      "Santa Teresa",
      "Cachoeiro de Itapemirim",
      "Alegre",
      "Domingos Martins",
      "Muniz Freire",
      "Viana",
      "Piúma",
      "Castelo",
      "Anchieta",
      "Mantenópolis",
      "Conceição da Barra",
      "Conceição do Castelo",
      "Santa Leopoldina",
      "São Gabriel da Palha",
      "Boa Esperança",
      "Sooretama",
      "São Roque do Canaã",
      "Vargem Alta",
      "Dores do Rio Preto",
      "Linhares",
      "Baixo Guandu",
      "Ibatiba",
      "Laranja da Terra",
      "Montanha",
      "Pancas",
      "Ressaca",
      "São José do Calçado",
      "São Pedro",
      "Santa Maria de Jetibá",
      "São João do Norte",
      "São José do Norte",
      "Afonso Cláudio",
      "Água Doce do Norte",
      "Barra de São Francisco",
    ],
  },
  {
    name: "Goiás",
    uf: "GO",
    municipios: [
      "Goiânia",
      "Aparecida de Goiânia",
      "Anápolis",
      "Rio Verde",
      "Luziânia",
      "Catalão",
      "Goiatuba",
      "Caldas Novas",
      "Jataí",
      "Formosa",
      "Itumbiara",
      "Uruaçu",
      "Quirinópolis",
      "Trindade",
      "Planaltina",
      "Águas Lindas de Goiás",
      "Santa Helena de Goiás",
      "Pirenópolis",
      "Ipameri",
      "Morrinhos",
      "Goianésia",
      "São Luís de Montes Belos",
      "Iporá",
      "Ceres",
      "Posse",
      "Cachoeira Alta",
      "Santo Antônio do Descoberto",
      "Brasabrantes",
      "Joviânia",
      "Fazenda Nova",
      "São Miguel do Araguaia",
      "Aragarças",
      "Cromínia",
      "Dianópolis",
      "Fazenda Rio Grande",
      "Inhumas",
      "Orizona",
      "Rianápolis",
      "Jussara",
      "Silvânia",
      "Mimoso de Goiás",
      "Vianópolis",
      "Buriti Alegre",
      "Cavalcante",
      "Montes Claros de Goiás",
      "Chapadão do Céu",
      "Mozarlândia",
      "Teresina de Goiás",
      "Rodeio",
      "São João da Paraúna",
      "Santa Tereza de Goiás",
      "Aurilândia",
      "Damianópolis",
      "Edéia",
      "Goiatuba",
      "Novo Brasil",
      "Nova Crixás",
      "Portelândia",
      "Doverlândia",
      "Iaciara",
    ],
  },
  {
    name: "Maranhão",
    uf: "MA",
    municipios: [
      "São Luís",
      "Imperatriz",
      "Caxias",
      "Timon",
      "Paço do Lumiar",
      "São José de Ribamar",
      "Bacabal",
      "Codó",
      "Barreirinhas",
      "Açailândia",
      "Santa Inês",
      "Buriticupu",
      "Chapadinha",
      "Pinheiro",
      "Viana",
      "Tuntum",
      "Rosário",
      "Balsas",
      "Pedreiras",
      "São João dos Patos",
      "Mirador",
      "Coroatá",
      "Itapecuru Mirim",
      "São Bernardo",
      "Icatu",
      "São Mateus do Maranhão",
      "Alto Alegre do Maranhão",
      "Colinas",
      "Bom Jardim",
      "Timon",
      "Sambaíba",
      "Santa Luzia",
      "Bacabeira",
      "São Domingos do Maranhão",
      "Vargem Grande",
      "São Luís Gonzaga do Maranhão",
      "Esperantinópolis",
      "Grajau",
      "Riachão",
      "Afonso Cunha",
      "Vitorino Freire",
      "São Vicente Ferrer",
      "São Francisco do Maranhão",
      "Anajatuba",
      "Rosário",
      "Caxias",
      "Lago da Pedra",
      "Carutapera",
      "Arari",
      "São João do Sóter",
      "Mirador",
      "São Pedro dos Crentes",
      "São José dos Basílios",
      "São João do Carú",
      "Bacabal",
      "Paço do Lumiar",
      "Açailândia",
      "Cururupu",
      "São Luís",
      "Alto Parnaíba",
      "Balsas",
      "São Francisco do Maranhão",
      "Santa Rita",
      "Turiaçu",
      "Bequimão",
    ],
  },
  {
    name: "Mato Grosso",
    uf: "MT",
    municipios: [
      "Cuiabá",
      "Várzea Grande",
      "Rondonópolis",
      "Sinop",
      "Tangará da Serra",
      "Sorriso",
      "Cáceres",
      "Lucas do Rio Verde",
      "Nova Mutum",
      "Chapada dos Guimarães",
      "Diamantino",
      "Colíder",
      "Juína",
      "São Félix do Araguaia",
      "Alta Floresta",
      "Primavera do Leste",
      "Porto Esperidião",
      "Jaciara",
      "Campo Verde",
      "Araguaína",
      "São José do Rio Claro",
      "Barra do Garças",
      "Campo Novo do Parecis",
      "Cláudia",
      "Nobres",
      "Cuiabá",
      "Ribeirão Cascalheira",
      "Rosário Oeste",
      "Nova Olímpia",
      "Guarantã do Norte",
      "Serra Nova Dourada",
      "Paranaíta",
      "São José dos Quatro Marcos",
      "Tangará da Serra",
      "Poconé",
      "Porto Alegre do Norte",
      "Apiacás",
      "Itiquira",
      "Cáceres",
      "Ponte Branca",
      "Juruena",
      "Comodoro",
      "Tapurah",
      "Nortelândia",
      "Sapezal",
      "Peixoto de Azevedo",
      "Santa Rita do Trivelato",
      "Mato Grosso",
      "São José do Xingu",
      "Vila Rica",
      "Dom Aquino",
      "São José do Povo",
      "Nova Canaã do Norte",
      "Santa Terezinha",
      "Cocalinho",
    ],
  },
  {
    name: "Mato Grosso do Sul",
    uf: "MS",
    municipios: [
      "Campo Grande",
      "Dourados",
      "Três Lagoas",
      "Corumbá",
      "Ponta Porã",
      "Sidrolândia",
      "Naviraí",
      "São Gabriel do Oeste",
      "Aquidauana",
      "Maracaju",
      "Paranaíba",
      "Jardim",
      "Nova Andradina",
      "Coxim",
      "Ivinhema",
      "Cassilândia",
      "Bela Vista",
      "Bataguassu",
      "Glória de Dourados",
      "Amambai",
      "Costa Rica",
      "Juti",
      "Selvíria",
      "Terenos",
      "Rio Brilhante",
      "São Pedro de Tacina",
      "Porto Murtinho",
      "Água Clara",
      "Fátima do Sul",
      "Chapadão do Sul",
      "Eldorado",
      "Santa Rita do Pardo",
      "Ladário",
      "Vicentina",
      "Nioaque",
      "Antônio João",
      "Paranaíba",
      "Pedro Gomes",
      "São João do Corumbá",
      "Taquarussu",
      "Inocência",
      "Nova Alvorada do Sul",
      "Corguinho",
      "Japorã",
      "Novo Horizonte do Sul",
      "Ponta Porã",
      "Rochedo",
      "Jaraguari",
      "Campo Grande",
      "Caarapó",
      "São José do Rio Preto",
      "Terenos",
      "Itaquiraí",
      "Itaquiraí",
      "Dourados",
      "Nova Andradina",
      "São Gabriel do Oeste",
      "Bataguassu",
      "Jardim",
      "Bela Vista",
      "Rio Brilhante",
      "Sidrolândia",
    ],
  },
  {
    name: "Minas Gerais",
    uf: "MG",
    municipios: [
      "Belo Horizonte",
      "Uberlândia",
      "Contagem",
      "Juiz de Fora",
      "Betim",
      "Montes Claros",
      "Ribeirão das Neves",
      "Ipatinga",
      "Uberaba",
      "Sete Lagoas",
      "Governador Valadares",
      "Varginha",
      "Poços de Caldas",
      "Santa Luzia",
      "Teófilo Otoni",
      "Divinópolis",
      "Tijucas",
      "Barbacena",
      "Itabira",
      "Pouso Alegre",
      "Timóteo",
      "São João Nepomuceno",
      "São Sebastião do Paraíso",
      "Manhuaçu",
      "Caratinga",
      "Nova Lima",
      "Formiga",
      "Araxá",
      "Araguari",
      "Diamantina",
      "Guaxupé",
      "Caxambu",
      "Lavras",
      "Montes Claros",
      "Três Corações",
      "Paracatu",
      "Carmo do Cajuru",
      "Patrocínio",
      "São João del-Rei",
      "Capelinha",
      "Itaúna",
      "Muriaé",
      "Barra Longa",
      "João Monlevade",
      "Nova Serrana",
      "Ribeirão Preto",
      "São Francisco",
      "Serro",
      "Viçosa",
      "Ponte Nova",
      "Bom Despacho",
      "São Gonçalo do Pará",
      "Santa Bárbara",
      "Conselheiro Lafaiete",
      "Serro",
      "Alfenas",
      "São Lourenço",
      "Maria da Fé",
      "Lavras",
      "Boa Esperança",
      "Igarapé",
      "São Sebastião do Oeste",
      "Iturama",
      "Coronel Fabriciano",
      "Carmo do Rio Claro",
      "Caldas",
    ],
  },
  {
    name: "Pará",
    uf: "PA",
    municipios: [
      "Belém",
      "Ananindeua",
      "Santarém",
      "Marabá",
      "Parauapebas",
      "Castanhal",
      "Bragança",
      "Altamira",
      "Barcarena",
      "Cametá",
      "São Félix do Xingu",
      "Tucuruí",
      "Redenção",
      "Tailândia",
      "Capanema",
      "Marituba",
      "Salinópolis",
      "Breves",
      "Portel",
      "Itaituba",
      "Conceição do Araguaia",
      "São João de Pirabas",
      "Mocajuba",
      "Monte Alegre",
      "Novo Progresso",
      "São Domingos do Araguaia",
      "São Geraldo do Araguaia",
      "Abaetetuba",
      "Rurópolis",
      "Santa Izabel do Pará",
      "Paragominas",
      "Ourém",
      "Aurora do Pará",
      "Inhangapi",
      "São Caetano de Odivelas",
      "Tucumã",
      "Soure",
      "Benevides",
      "Curralinho",
      "Juruena",
      "Marabá",
      "Placas",
      "São Sebastião da Boa Vista",
      "Barreiro",
      "Oriximiná",
      "Moju",
      "Paragominas",
      "Salvaterra",
      "São João do Araguaia",
      "Prainha",
      "Igarapé-Miri",
      "Melgaço",
      "Terra Santa",
      "Rondon do Pará",
      "Viseu",
      "Santa Maria das Barreiras",
      "São João do Araguaia",
      "Rio Maria",
      "Irituia",
      "São Francisco do Pará",
      "Limoeiro do Ajuru",
      "Água Azul do Norte",
      "São Miguel do Guamá",
      "Curuá",
      "Cametá",
    ],
  },
  {
    name: "Rio Grande do Sul",
    uf: "RS",
    municipios: [
      "Porto Alegre",
      "Caxias do Sul",
      "Pelotas",
      "Santa Maria",
      "Gravataí",
      "São Leopoldo",
      "Novo Hamburgo",
      "Canoas",
      "Uruguaiana",
      "Bagé",
      "Santana do Livramento",
      "Rio Grande",
      "São Borja",
      "Ijuí",
      "Erechim",
      "Sapucaia do Sul",
      "São José do Norte",
      "São Sebastião do Caí",
      "Esteio",
      "Teutônia",
      "Panambi",
      "Tramandaí",
      "Rio Pardo",
      "Lajeado",
      "Capão da Canoa",
      "Sapiranga",
      "São Francisco de Assis",
      "São Gabriel",
      "Camaquã",
      "Marau",
      "São Luiz Gonzaga",
      "Santo Ângelo",
      "Sananduva",
      "Cruz Alta",
      "Carazinho",
      "Tapes",
      "Santa Cruz do Sul",
      "Bom Princípio",
      "Mariana Pimentel",
      "São Vicente do Sul",
      "Venâncio Aires",
      "Cruz Alta",
      "Dom Pedrito",
      "Júlio de Castilhos",
      "Santa Maria do Herval",
      "Jari",
      "Coqueiro Baixo",
      "São Martinho",
      "Ronda Alta",
      "Marcelino Ramos",
      "Picada Café",
      "Jacuizinho",
      "Boqueirão do Leão",
      "Taquara",
      "Entre-Ijuís",
      "Porto Xavier",
      "Seberi",
      "Arroio do Meio",
      "Nova Santa Rita",
      "Serafina Corrêa",
      "São João da Urtiga",
      "Carlos Barbosa",
      "Colinas",
      "Bom Jesus",
      "Santa Rosa",
      "Tapera",
      "Santo Antônio da Patrulha",
      "São Pedro do Sul",
      "Piratini",
      "Taquari",
      "Alvorada",
      "Carlos Gomes",
      "Candelária",
      "Cruzaltense",
    ],
  },
  {
    name: "Paraná",
    uf: "PR",
    municipios: [
      "Curitiba",
      "Londrina",
      "Maringá",
      "Ponta Grossa",
      "Foz do Iguaçu",
      "Cascavel",
      "São José dos Pinhais",
      "Araucária",
      "Guarapuava",
      "Toledo",
      "Paranaguá",
      "Colombo",
      "Campo Largo",
      "Campo Mourão",
      "Apucarana",
      "União da Vitória",
      "Ibiporã",
      "Paranavaí",
      "Mato Rico",
      "Irati",
      "São Miguel do Iguaçu",
      "Telêmaco Borba",
      "Guaíra",
      "Medianeira",
      "Pato Branco",
      "Santo Antônio da Platina",
      "Lapa",
      "Prudentópolis",
      "Cianorte",
      "Laranjeiras do Sul",
      "Ibiporã",
      "Campo Mourão",
      "Jandaia do Sul",
      "Ivaiporã",
      "Alto Paraná",
      "Santa Helena",
      "Quedas do Iguaçu",
      "Peabiru",
      "Cruz Machado",
      "Assis Chateaubriand",
      "Cambé",
      "Paranavaí",
      "Maringá",
      "São João do Ivaí",
      "Umuarama",
      "São Mateus do Sul",
      "Sengés",
      "Rancho Alegre",
      "São José da Boa Vista",
      "São Pedro do Iguaçu",
      "Guarapuava",
      "Wenceslau Braz",
      "Rondon",
      "Boa Vista da Aparecida",
      "Nova Esperança",
      "Medianeira",
      "Guaíra",
      "Tamarana",
      "Manfrinópolis",
      "Foz do Iguaçu",
      "Virmond",
      "Sarandi",
      "Londrina",
      "Guarapuava",
      "Palotina",
      "Santa Tereza do Oeste",
      "Laranjeiras do Sul",
      "Lapa",
      "Ibiporã",
    ],
  },
  {
    name: "Rondônia",
    uf: "RO",
    municipios: [
      "Porto Velho",
      "Ji-Paraná",
      "Ariquemes",
      "Cacoal",
      "Rolim de Moura",
      "Vilhena",
      "Buritis",
      "Jaru",
      "Pimenta Bueno",
      "Ouro Preto do Oeste",
      "São Francisco do Guaporé",
      "Guajará-Mirim",
      "Alta Floresta d'Oeste",
      "Machadinho d'Oeste",
      "Monte Negro",
      "Cujubim",
      "Castanheiras",
      "Espigão d'Oeste",
      "Nova Brasilândia d'Oeste",
      "Mirante da Serra",
      "Vale do Anari",
      "Chupinguaia",
      "Novo Horizonte do Oeste",
      "Jaru",
      "São Miguel do Guaporé",
      "Campo Novo de Rondônia",
      "Itapuã do Oeste",
      "Pimenteiras do Oeste",
      "Santa Luzia d'Oeste",
      "Corumbiara",
      "Seringueiras",
      "São Felipe d'Oeste",
      "Presidente Médici",
      "Cabixi",
      "Candeias do Jamari",
      "Alvorada d'Oeste",
      "São Domingos d'Oeste",
      "Governador Jorge Teixeira",
      "Teixeirópolis",
      "Rio Crespo",
      "São Francisco do Guaporé",
      "Jaru",
      "Castanheiras",
      "Cujubim",
      "Guajará-Mirim",
      "Machadinho d'Oeste",
      "Mirante da Serra",
      "Nova Brasilândia d'Oeste",
      "Ouro Preto do Oeste",
      "Vilhena",
    ],
  },
  {
    name: "Roraima",
    uf: "RR",
    municipios: [
      "Boa Vista",
      "Rorainópolis",
      "Caracaraí",
      "São João da Baliza",
      "São Luiz",
      "Uiramuta",
      "Mucajaí",
      "Normandia",
      "Bonfim",
      "Canta",
      "Amajari",
      "Iracema",
      "Pacaraima",
      "Cantá",
      "Santa Maria do Boiaçu",
      "Serrinha",
      "São Sebastião",
      "São José do Rio Claro",
      "Mucajaí",
      "Raposa",
      "Vila Avaliação",
      "Vila do Trinta",
      "Vila de São José",
    ],
  },
  {
    name: "Santa Catarina",
    uf: "SC",
    municipios: [
      "Florianópolis",
      "Joinville",
      "Blumenau",
      "Chapecó",
      "Criciúma",
      "São José",
      "Itajaí",
      "Lages",
      "Jaraguá do Sul",
      "Balneário Camboriú",
      "Tubarão",
      "Araranguá",
      "São Bento do Sul",
      "Camboriú",
      "Palhoça",
      "Concórdia",
      "Rio do Sul",
      "Caçador",
      "Braço do Norte",
      "Pomerode",
      "São Miguel do Oeste",
      "Xanxerê",
      "Pinhalzinho",
      "Videira",
      "Mafra",
      "Mondaí",
      "Forquilhinha",
      "Imbituba",
      "Joaçaba",
      "São João Batista",
      "São Francisco do Sul",
      "Barra Velha",
      "Massaranduba",
      "Guaramirim",
      "Tubarão",
      "Criciúma",
      "Seara",
      "Tigrinhos",
      "Agronômica",
      "Bandeirante",
      "Rio Negrinho",
      "Rancho Queimado",
      "Santa Cecília",
      "Serra Alta",
      "Xavantina",
      "Ipumirim",
      "Chapecó",
      "João Pessoa",
      "Concordia",
      "São João do Sul",
      "São José do Cerrito",
      "Joaçaba",
      "Bom Retiro",
      "Içara",
      "Campo Alegre",
      "Timbó",
      "Lauro Müller",
      "Capinzal",
      "Salto Veloso",
    ],
  },
  {
    name: "São Paulo",
    uf: "SP",
    municipios: [
      "São Paulo",
      "Guarulhos",
      "Campinas",
      "São Bernardo do Campo",
      "São José dos Campos",
      "Santo André",
      "Ribeirão Preto",
      "Osasco",
      "Sorocaba",
      "Mogi das Cruzes",
      "Jundiaí",
      "Bauru",
      "Indaiatuba",
      "São Vicente",
      "Diadema",
      "São Caetano do Sul",
      "Araraquara",
      "Itaquaquecetuba",
      "Tatuí",
      "Mauá",
      "Botucatu",
      "Suzano",
      "Praia Grande",
      "Santos",
      "Franca",
      "São João da Boa Vista",
      "Barueri",
      "São Roque",
      "Itapetininga",
      "Jaú",
      "Monte Alto",
      "Catanduva",
      "Jaboticabal",
      "Votorantim",
      "Itapeva",
      "Ourinhos",
      "Mococa",
      "Tupã",
      "Matão",
      "São Pedro",
      "Lins",
      "Santa Bárbara d'Oeste",
      "Limeira",
      "Tatuí",
      "Águas de São Pedro",
      "Espirito Santo do Pinhal",
      "Amparo",
      "Paraguaçu Paulista",
      "Valinhos",
      "Itatiba",
      "Salto",
      "Serra Negra",
      "São Sebastião",
      "Tremembé",
      "Guarujá",
      "Bertioga",
      "São Carlos",
      "Piracicaba",
      "Cubatão",
      "Santo Antônio do Jardim",
      "Cajamar",
      "São José do Rio Preto",
      "São Miguel Arcanjo",
      "Itapira",
      "Campo Limpo Paulista",
      "Bragança Paulista",
      "Guarulhos",
      "Suzano",
      "Boituva",
      "Barretos",
      "Palmeiras de Goiás",
      "Botucatu",
    ],
  },
  {
    name: "Sergipe",
    uf: "SE",
    municipios: [
      "Aracaju",
      "Nossa Senhora do Socorro",
      "Lagarto",
      "Itabaiana",
      "Estância",
      "São Cristóvão",
      "Barra dos Coqueiros",
      "Simão Dias",
      "Laranjeiras",
      "Propriá",
      "Neópolis",
      "Tobias Barreto",
      "Capela",
      "Sergipe",
      "Canindé do São Francisco",
      "Japaratuba",
      "Boquim",
      "Itaporanga d'Ajuda",
      "Pedra Mole",
      "Santa Luzia do Itanhy",
      "São Miguel do Aleixo",
      "Aquidabã",
      "Brejo Grande",
      "Carmópolis",
      "Indiaroba",
      "General Maynard",
      "Riachuelo",
      "Malhada dos Bois",
      "São Domingos",
      "Areia Branca",
      "Divina Pastora",
      "N. Senhora de Lourdes",
      "São José de Ribamar",
      "Santa Rosa de Lima",
      "Santa Tereza do Oeste",
      "Santo Amaro das Brotas",
      "São Francisco",
      "Pinhão",
      "Itabi",
      "São José dos Campos",
      "Poço Redondo",
      "Santa Maria",
      "Malhador",
      "Santana do São Francisco",
      "Capela",
      "Tobias Barreto",
      "Riachão do Dantas",
      "Barra dos Coqueiros",
      "São Paulo",
      "São João de Pirabas",
    ],
  },
  {
    name: "Tocantins",
    uf: "TO",
    municipios: [
      "Palmas",
      "Araguaína",
      "Gurupi",
      "Porto Nacional",
      "Paraíso do Tocantins",
      "Colinas do Tocantins",
      "Tocantinópolis",
      "Miracema do Tocantins",
      "Augustinópolis",
      "Tupiratins",
      "Alvorada",
      "Dianópolis",
      "Pium",
      "Formoso do Araguaia",
      "Guaraí",
      "São Valério da Natividade",
      "Lajeado",
      "Ponte Alta do Tocantins",
      "Recursolândia",
      "Carmolândia",
      "Aurora do Tocantins",
      "Campos Lindos",
      "Mateiros",
      "Itacajá",
      "Araguatins",
      "Santa Fé do Araguaia",
      "Riachinho",
      "Santa Tereza do Tocantins",
      "Natividade",
      "Nova Rosalândia",
      "Figueirópolis",
      "Brejinho de Nazaré",
      "Dueré",
      "Pequizeiro",
      "São Sebastião do Tocantins",
      "Chapada de Areia",
      "Crixás do Tocantins",
      "Filadélfia",
      "Lagoa da Confusão",
      "Sampaio",
      "Juarina",
      "Tocantínia",
      "São Miguel do Tocantins",
      "Silvanópolis",
      "Buriti do Tocantins",
      "Pau D'Arco",
      "Palmeiras do Tocantins",
      "Divinópolis do Tocantins",
      "Pedro Afonso",
      "Teresina do Tocantins",
      "Sampaio",
      "São Salvador do Tocantins",
      "Araguacema",
      "Araguanã",
      "Tocantins",
    ],
  },
];

export default EstateFilter;
